spring:
    # autoconfigure:
    #     exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    application:
        name: users
    datasource:
        url: jdbc:h2:file:./data/testdb
        username: "sa"
        password: "pass"
        driver-class-name: org.h2.Driver
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create-drop # Hibernate ddl auto (create, create-drop, validate, update, none)
        defer-datasource-initialization: true
    sql:    
        init:
            mode: always
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ  # Formato ISO 8601
        time-zone: UTC
        serialization:
            write-dates-as-timestamps: false  # Desactivar serialización como array

# swagger-ui custom path
springdoc:
    swagger-ui:
        path: /swagger-ui.html

server:
    servlet:
        context-path: /api/v1

security:
    jwt:
        expiration-in-minutes: 30
        secret-key: ZXN0YSBlcyBtaSBjb250cmFzZW5hIHNlZ3VyYSAxMjM0NTY3ODkgQUJDYWJj

logging:
    level:
        root: INFO
        org:
            springframework:
                security: DEBUG
            h2: DEBUG